import io

# ==============================================================================
# MONTHLY ROI REPORT GENERATOR
# ==============================================================================

def generate_monthly_roi_report(branding, total_revenue, reviews, pipeline):
    """
    Compiles a 1-page "Executive Summary" text-based report for download.
    In a full production environment, this could use `reportlab` or `fpdf` to generate true PDFs.
    Here we simulate a pristine markdown/text report that serves the exact same ROI purpose.
    """
    
    # Calculate some dynamic metrics for the report
    new_5_star = len([r for r in reviews if r.get('rating') == 5])
    
    # Identify "Hot" Leads (Assumes pipeline has 'warmth' scored out of 10)
    hot_leads = sorted([l for l in pipeline if l.get('warmth', 0) >= 8], key=lambda x: x.get('warmth', 0), reverse=True)
    top_3_leads = hot_leads[:3]
    
    # Build Report Content
    content = f"""====================================================================
               EXECUTIVE ROI SUMMARY: {branding['business_name'].upper()}
====================================================================
Sovereign Vault Automated Report
--------------------------------------------------------------------

1. OVERVIEW
   This month, your fully automated local dominance infrastructure 
   has successfully captured and converted high-intent search traffic 
   directly into bottom-line revenue.

2. FINANCIAL IMPACT
   Total Attributed Revenue: ${total_revenue:,.2f}
   (Calculated via automated WhatsApp appointment bookings)

3. REPUTATION VELOCITY
   New 5-Star Reviews Captured: {new_5_star}
   Status: The system continues to automatically dispatch review 
   requests to completed appointments, steadily pushing your 
   Google ranking upward.

4. TOP 3 HOT LEADS (READY TO CLOSE)
"""
    
    if top_3_leads:
        for idx, lead in enumerate(top_3_leads, 1):
            content += f"   [{idx}] Name: {lead.get('name', 'Unknown')}\n"
            content += f"       Intent: {lead.get('interest', 'General')}\n"
            content += f"       Message: \"{lead.get('message', '')}\"\n"
            content += f"       AI Warmth Score: {lead.get('warmth', 0)}/10\n\n"
    else:
        content += "   No hot leads currently trapped in the pipeline this week.\n\n"
        
    content += f"""--------------------------------------------------------------------
Generated by Sovereign OS | {branding['business_name']} Growth Engine
===================================================================="""

    # Convert string to BytesIO for Streamlit st.download_button
    bio = io.BytesIO()
    bio.write(content.encode('utf-8'))
    bio.seek(0)
    
    return bio
